name: Generate 3D Contribution Calendar

on:
  schedule:
    - cron: "0 8 * * *" # runs daily at 08:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate 3D contributions
        uses: yoshi389111/github-profile-3d-contrib@v2
        with:
          username: "NimaJafariComp"

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update 3D contributions"
